language: php

cache:
  directories:
    - $HOME/.composer/cache/files

# https://docs.travis-ci.com/user/build-stages

jobs:

  include:

    - stage: test

      php: 7.3

      before_script:
        - travis_retry composer self-update
        - travis_retry composer update --prefer-lowest --no-ansi --no-interaction --no-progress --no-scripts
        - vendor/bin/phpunit --dump-xdebug-filter xdebug-filter.php

      script:
        # - vendor/bin/phpunit --prepend xdebug-filter.php --coverage-html coverage
        - vendor/bin/phpunit --prepend xdebug-filter.php --coverage-text --coverage-clover=coverage.clover

      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    - stage: deploy

      name: "Documentation"

      if: branch = master

      php: 7.3

      before_script:
        - git clone https://github.com/mtvbrianking/laravel-package-boilerplate.git

      install:
        - curl -O http://get.sensiolabs.org/sami.phar

      script:
       - php sami.phar update .sami.dist

      # https://docs.travis-ci.com/user/deployment/pages/
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: docs
        on:
          branch: master

# https://docs.travis-ci.com/user/notifications
notifications:
  email:
    on_success: never
    on_failure: always
